name: Dependabot manager

on:
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Dependabot updates
        uses: aribanerjee/Dependabot-manager@v1.0.6
        with:
          package-ecosystem: 'npm'
